# .github/workflows/deploy-ftp.yml
name: Deploy static HTML via FTP

on:
  push:
    branches: [ main ]
    paths:
      - 'public/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hostinger   # 👈 Aquí vinculas el job con el environment
    steps:
      - uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: public/
          server-dir: /domains/clubpadelandujar.com/public_html/wp-content/themes/inspiro
          exclude: |
            **/.git*
            **/.github/**
